### ISSUE TITLE
ensure all lints are relevant in Dart 2

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#1372]
In cases where rules can be updated and remain valuable we should do so.  If lints are no longer relevant we should deprecate and remove (e.g., #1220). 

- [x] deprecate `prefer_bool_in_asserts` #1266
- [x] deprecate `super_goes_last`

**Comment by pq** [comment]
In https://github.com/dart-lang/linter/issues/1368#issuecomment-455253837, @kwalrath writes:

[W]e should certainly remove lints that are irrelevant or problematic in Dart 2. Some used to be in the style guide but were removed (see dart-lang/site-www#863, dart-lang/site-www#889, and other changes to Effective Dart). Here are some possibilities:

- [ ] `always_declare_return_types`
- [ ] `avoid_types_on_closure_parameters`
- [ ] `type_annotate_public_apis`
- [ ] `super_goes_last`: Irrelevant because Dart 2 enforces this. (I can't find this in the SDK changelog, but it's mentioned in dart-lang/site-www#863.)
- [ ] `prefer_constructors_over_static_methods`: Irrelevant from the POV of reading code (though not from the implementer's or doc reader's POV).

**Comment by pq** [comment]
This will be ongoing.  Let's open new issues as new concerns arise.
