### ISSUE TITLE
`package:linter` nnbd migration plan

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#2453]
The `package:linter` migration plan:

- [x] 1. land an initial migration that is as tool-driven as possible that runs tests, etc in unsound mode (@pq)
- [x] 2. follow-up with changes to tidy up `lib` (e.g., remove unnecessary null operators) (@pq) (see: https://github.com/dart-lang/linter/pull/2452#pullrequestreview-589866184)
- [x] 3. cleanup `tool` (gated somewhat by `dev_dependencies` such as `github`) (@pq)
- [x] 4. fix-up build scripts and remove `unsound` flags (https://github.com/dart-lang/linter/pull/2467)

1. and 2. will happen before a release (3 is stretch).

Related issues:

https://github.com/SpinlockLabs/github.dart/issues/236

In conversation, @bwilkerson and I agreed (again) how nice it would be to have some lints to disallow ~`?`s and~ `!`s as this would help in tidying.  (I think @scheglov is wanting something similar.)

**Comment by bwilkerson** [comment]
To be clear, I don't think we want a lint to disallow `?`s. There are times when they're necessary. I just want one to disallow null checks because I think they're almost always wrong.

**Comment by scheglov** [comment]
I thought so too, that `Type?` and `?.` are useful and are not unsafe.
But `!` null checks are unsafe.

**Comment by pq** [comment]
Sorry yes, I wrote in haste.  I 100% agree.
