### ISSUE TITLE
☂️  linter implementation for named arguments anywhere

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/linter#3050]
See dart-lang/sdk#47451 for the meta issue and dart-lang/language#1072 for the language issue.

---

- [x] https://github.com/dart-lang/linter/issues/3082
- [x] ~https://github.com/dart-lang/linter/issues/3084~
- [x] ~https://github.com/dart-lang/linter/issues/3085~

**Comment by devoncarew** [comment]
Hmm - from looking at the checkboxes above, it looks like this item might be complete?

**Comment by pq** [comment]
Not sure.  Those were just the issues that came up on a first pass through the spec.  I'll carve out some time to do a more thorough review in the next week.

**Comment by devoncarew** [comment]
Gotcha, makes sense; just wanted to be able to toggle this if the work was in fact complete.
