### ISSUE TITLE
☂️  [task] remove `DartProject`

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#3395]
`DartProject` has never worked completely w/ server (see https://github.com/dart-lang/linter/issues/154) and since it's creation, `LinterContext` has been introduced which, moving forward, is the right way to answer the kinds of questions it was designed to address.  Since the lints that are currently using it are failing fast, my thinking is that we can safely remove all references to it from the existing lints as a non-breaking change.  We can then follow-up with a new set of changes that updates the (already) broken lints to use `LinterContext` methods.  These changes will produce a bunch of new diagnostics which though (now) correct may have ecosystem impact so we'll want to carefully vet their roll-out.

---

## Plan

- [x] remove `DartProject` lint references
  - [x] `directives_ordering` (https://github.com/dart-lang/linter/pull/3397)
  - [x] `package_api_docs` (https://github.com/dart-lang/linter/pull/3398)
  - [x] `package_prefixed_library_names` (https://github.com/dart-lang/linter/pull/3399)
- [x] deprecate `DartProject` (and visitor) in analyzer (https://dart-review.googlesource.com/c/sdk/+/244760)
- [x] remove `DartProject` from analyzer (in a breaking change release) (https://dart-review.googlesource.com/c/sdk/+/245240)
- [ ] fix functionality in:
  - [ ] `directives_ordering`
  - [ ] `package_api_docs`
  - [ ] `package_prefixed_library_names`

**Comment by pq** [comment]
This is at a natural stopping point.  If the functionality additions get picked up, they can get tracked in their own issues.
