### ISSUE TITLE
☂️ [tracking] rename lints

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#3827]
A host of lints have prescriptive language in the names (e.g., prefixes like `prefer` and `avoid`).  Historically, these reflected language in the style guide and seemed to make sense at the time.  In retrospect this choice has some significant downsides and there have been a number of conversations about a big rename.  This issue is a **tracking issue** for such an effort.

The current suggestion for naming is more neutral:

> [Lints should be given a] short name using [Dart package naming conventions](https://dart.dev/tools/pub/pubspec#name). Naming is hard but strive to be concise and consistent. Prefer to use the problem as the name, as in the existing lints control_flow_in_finally and empty_catches. Do not start a lint's name with "always", "avoid", or "prefer". Where possible, use existing rules for inspiration and observe the rules of [parallel construction](https://en.wikipedia.org/wiki/Parallelism_(grammar)).

(from [writing-lints.md](https://github.com/dart-lang/linter/blob/main/doc/writing-lints.md)).

The goal is to update all lints to this new guidance.

Concretely, I propose we

-  [ ] identify lints that should be renamed
-  [ ] settle on an _aliasing approach_ so we can safely **_deprecate_** unfavored names
-  [ ] ensure that `dart fix` can perform the renames

I've got some thoughts on all 3 and will fill in some more details here but any early (and ongoing feedback) welcome!

**Comment by srawlins** [comment]
I think we should also rename `unnecessary_parenthesis` to `unnecessary_parentheses`. Most rules use plural text to describe a pattern that a developer should use or avoid, but this rule seems to go out of its way to call out the singular form of "parentheses."

**Comment by bwilkerson** [comment]
And the name is wrong because you can't have a single parenthesis that's unnecessary; either they're both necessary or they're both unnecessary. :-)

**Comment by parlough** [comment]
As I think more and more about documentation and discovery, I'm increasingly worried about the status of linter rule names.

Some are positive and/or instructional, well others (like diagnostics) are about the problem. 

I think the benefits to standardization are pretty large.

First in terms of choosing lints, the inconsistency results in developers not being able to fully rely on just the name to understand it's goal. We have a lot of lints now, so being able to gain interest from just the name is pretty valuable.

Second, as users are programming, receiving a lint in their IDE or by `dart analyze`, they shouldn't have to think about lint diagnostics differently than other diagnostics. Having their names be more consistent with other diagnostics could help their understanding and workflow.

If we have a mechanism to rename that `dart fix` can handle and we can be aware of from the documentation for redirects, I think this would be worthwhile, especially if we can get closer to the other diagnostics.

**Comment by bwilkerson** [comment]
I agree with all of that, and I'd like to see the lint names be more consistent. From my perspective it's primarily a question of priorities; is renaming lints more important than adding more quick fixes or refactorings, etc.

**Comment by parlough** [comment]
That makes complete sense to me, just wanted to add my thoughts as I'm looking through them :) 

My initial feeling is that fixes/refactoring/etcs are more important, and hopefully as the cadence of new lints is reduced and the backlog of diagnostics are worked through, we can slowly catch up and revisit this in future.
