### ISSUE TITLE
0.1.30 Release Plan

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#477]
Punch list for a `0.1.30` release.

## Plan items

  * [x] update `invariant_booleans` docs (#476)
  * [x] fix false positive for `unnecessary_lambdas` (#473)
  * [x] land `use_initializing_formals_when_possible` (#475)
  * [x] do some rule renaming for consistency (#489)
  * [x] update changelist, pubspec
  * [x] update `AUTHORS` (#511)
  * [x] land `invariant_booleans` perf fixes (#501)

## Releasing

  * [x] tag release ([tag/0.1.30](https://github.com/dart-lang/linter/releases/tag/0.1.30))
  * [x] publish package (#438)
  * [x] publish docs ( https://github.com/dart-lang/linter/pull/384#issuecomment-284485488 ) 
  * [x] update `DEPS` (#491)

@alexeieleusis, @JPaulsen : are there any changes you have pending that are close to landing?

**Comment by alexeieleusis** [comment]
https://github.com/dart-lang/linter/pull/475 should land soon and we found some false positives for unnecessary_lambdas, should land soon too.

I think we should wait to fix the false positives because it certainly can change the programs in unintended ways. Or at least disable it.

**Comment by alexeieleusis** [comment]
I should have said @a14n found some false positives, not us. Thank you!

**Comment by alexeieleusis** [comment]
https://github.com/dart-lang/linter/issues/473 is the issue to fix.

**Comment by pq** [comment]
Thanks @alexeieleusis!  Updated punch list.

**Comment by pq** [comment]
Given the ongoing conversation on #473, should we maybe just disable  `unnecessary_lambdas` for this release?  We can follow-up with another as soon as we feel good about a proper fix.

@JPaulsen @alexeieleusis ?

**Comment by JPaulsen** [comment]
@pq I have the final fist almost ready, I think I will have it before 12:30 to check (actually I finished implementing it, I am writing more tests to have better test coverage)

**Comment by pq** [comment]
Nice.  Thanks for the update @JPaulsen !

**Comment by pq** [comment]
Updated punchlist with a new task to do some naming normalization.  (I was starting on a changelist and noticed that we have some names that don't play that well with our existing ones.)  I'll follow-up with a PR.

**Comment by alexeieleusis** [comment]
Awesome, thank you @pq .

**Comment by alexeieleusis** [comment]
@JPaulsen has a very interesting idea regarding performance of invariant_booleans and also has some progress on it, probably not worth delaying the release, but soon might be fixed.

**Comment by pq** [comment]
In the home stretch...

Unless folks feel strongly, I'd like to cut the branch.  We can follow-up quickly with a fresh patch if needed.  (FWIW: I'd like to get back into a monthly -- at least -- release cadence.)

cc @alexeieleusis @JPaulsen @srawlins

**Comment by alexeieleusis** [comment]
@JPaulsen seems to be done with the performance fix for invariant_boolean, it is no longer a slow lint, I would say we wait for it, is almost ready for review.

**Comment by pq** [comment]
Sounds good @alexeieleusis.  Thanks @JPaulsen! 👍

**Comment by pq** [comment]
Quick update: the plan of record is to cut this from https://github.com/dart-lang/linter/commit/f451f4cac6f57de256eb4f99371182525dbeb6c5 (@JPaulsen 's excellent `invariant_boolean`s fix). 🎂

**Comment by pq** [comment]
Actually, bumping forward to 2d2bd8d18e74249f9c7cd845f7fde141fada7e63 (for @a14n 's fix to `do_not_check_for_null_in_equality_operators`).

**Comment by pq** [comment]
At long last, landed!
