### ISSUE TITLE
[macros] linter support

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#4881]
A meta-issue to discuss and track work on linter support for macros.

[Feature Spec](https://github.com/dart-lang/language/blob/main/working/macros/feature-specification.md)

## Existing Lints

Some existing lints will need tests (minimally) and possibly enhanced implementations.

- [ ] [macros] evaluate support for `always_declare_return_types`
- [ ] [macros] evaluate support for `always_put_control_body_on_new_line`
- [ ] [macros] evaluate support for `always_put_required_named_parameters_first`
- [ ] [macros] evaluate support for `always_specify_types`
- [ ] [macros] evaluate support for `always_use_package_imports`
- [ ] [macros] evaluate support for `annotate_overrides`
- [ ] [macros] evaluate support for `annotate_redeclares`
- [ ] [macros] evaluate support for `avoid_annotating_with_dynamic`
- [ ] [macros] evaluate support for `avoid_bool_literals_in_conditional_expressions`
- [ ] [macros] evaluate support for `avoid_catches_without_on_clauses`
- [ ] [macros] evaluate support for `avoid_catching_errors`
- [ ] [macros] evaluate support for `avoid_classes_with_only_static_members`
- [ ] [macros] evaluate support for `avoid_double_and_int_checks`
- [ ] [macros] evaluate support for `avoid_dynamic_calls`
- [ ] [macros] evaluate support for `avoid_empty_else`
- [ ] [macros] evaluate support for `avoid_equals_and_hash_code_on_mutable_classes`
- [ ] [macros] evaluate support for `avoid_escaping_inner_quotes`
- [ ] [macros] evaluate support for `avoid_field_initializers_in_const_classes`
- [ ] [macros] evaluate support for `avoid_final_parameters`
- [ ] [macros] evaluate support for `avoid_function_literals_in_foreach_calls`
- [ ] [macros] evaluate support for `avoid_implementing_value_types`
- [ ] [macros] evaluate support for `avoid_init_to_null`
- [ ] [macros] evaluate support for `avoid_js_rounded_ints`
- [ ] [macros] evaluate support for `avoid_multiple_declarations_per_line`
- [ ] [macros] evaluate support for `avoid_null_checks_in_equality_operators`
- [ ] [macros] evaluate support for `avoid_positional_boolean_parameters`
- [ ] [macros] evaluate support for `avoid_print`
- [ ] [macros] evaluate support for `avoid_private_typedef_functions`
- [ ] [macros] evaluate support for `avoid_redundant_argument_values`
- [ ] [macros] evaluate support for `avoid_relative_lib_imports`
- [ ] [macros] evaluate support for `avoid_renaming_method_parameters`
- [ ] [macros] evaluate support for `avoid_return_types_on_setters`
- [ ] [macros] evaluate support for `avoid_returning_null_for_void`
- [ ] [macros] evaluate support for `avoid_returning_this`
- [ ] [macros] evaluate support for `avoid_setters_without_getters`
- [ ] [macros] evaluate support for `avoid_shadowing_type_parameters`
- [ ] [macros] evaluate support for `avoid_single_cascade_in_expression_statements`
- [ ] [macros] evaluate support for `avoid_slow_async_io`
- [ ] [macros] evaluate support for `avoid_type_to_string`
- [ ] [macros] evaluate support for `avoid_types_as_parameter_names`
- [ ] [macros] evaluate support for `avoid_types_on_closure_parameters`
- [ ] [macros] evaluate support for `avoid_unnecessary_containers`
- [ ] [macros] evaluate support for `avoid_unused_constructor_parameters`
- [ ] [macros] evaluate support for `avoid_void_async`
- [ ] [macros] evaluate support for `avoid_web_libraries_in_flutter`
- [ ] [macros] evaluate support for `await_only_futures`
- [ ] [macros] evaluate support for `camel_case_extensions`
- [ ] [macros] evaluate support for `camel_case_types`
- [ ] [macros] evaluate support for `cancel_subscriptions`
- [ ] [macros] evaluate support for `cascade_invocations`
- [ ] [macros] evaluate support for `cast_nullable_to_non_nullable`
- [ ] [macros] evaluate support for `close_sinks`
- [ ] [macros] evaluate support for `collection_methods_unrelated_type`
- [ ] [macros] evaluate support for `combinators_ordering`
- [ ] [macros] evaluate support for `comment_references`
- [ ] [macros] evaluate support for `conditional_uri_does_not_exist`
- [ ] [macros] evaluate support for `constant_identifier_names`
- [ ] [macros] evaluate support for `control_flow_in_finally`
- [ ] [macros] evaluate support for `curly_braces_in_flow_control_structures`
- [ ] [macros] evaluate support for `dangling_library_doc_comments`
- [ ] [macros] evaluate support for `depend_on_referenced_packages`
- [ ] [macros] evaluate support for `deprecated_consistency`
- [ ] [macros] evaluate support for `deprecated_member_use_from_same_package`
- [ ] [macros] evaluate support for `diagnostic_describe_all_properties`
- [ ] [macros] evaluate support for `directives_ordering`
- [ ] [macros] evaluate support for `discarded_futures`
- [ ] [macros] evaluate support for `do_not_use_environment`
- [ ] [macros] evaluate support for `empty_catches`
- [ ] [macros] evaluate support for `empty_constructor_bodies`
- [ ] [macros] evaluate support for `empty_statements`
- [ ] [macros] evaluate support for `eol_at_end_of_file`
- [ ] [macros] evaluate support for `erase_dart_type_extension_types`
- [ ] [macros] evaluate support for `exhaustive_cases`
- [ ] [macros] evaluate support for `file_names`
- [ ] [macros] evaluate support for `flutter_style_todos`
- [ ] [macros] evaluate support for `hash_and_equals`
- [ ] [macros] evaluate support for `implementation_imports`
- [ ] [macros] evaluate support for `implicit_call_tearoffs`
- [ ] [macros] evaluate support for `implicit_reopen`
- [ ] [macros] evaluate support for `invalid_case_patterns`
- [ ] [macros] evaluate support for `join_return_with_assignment`
- [ ] [macros] evaluate support for `leading_newlines_in_multiline_strings`
- [ ] [macros] evaluate support for `library_annotations`
- [ ] [macros] evaluate support for `library_names`
- [ ] [macros] evaluate support for `library_prefixes`
- [ ] [macros] evaluate support for `library_private_types_in_public_api`
- [ ] [macros] evaluate support for `lines_longer_than_80_chars`
- [ ] [macros] evaluate support for `literal_only_boolean_expressions`
- [ ] [macros] evaluate support for `matching_super_parameters`
- [ ] [macros] evaluate support for `missing_whitespace_between_adjacent_strings`
- [ ] [macros] evaluate support for `no_adjacent_strings_in_list`
- [ ] [macros] evaluate support for `no_default_cases`
- [ ] [macros] evaluate support for `no_duplicate_case_values`
- [ ] [macros] evaluate support for `no_leading_underscores_for_library_prefixes`
- [ ] [macros] evaluate support for `no_leading_underscores_for_local_identifiers`
- [ ] [macros] evaluate support for `no_literal_bool_comparisons`
- [ ] [macros] evaluate support for `no_logic_in_create_state`
- [ ] [macros] evaluate support for `no_runtimeType_toString`
- [ ] [macros] evaluate support for `no_self_assignments`
- [ ] [macros] evaluate support for `no_wildcard_variable_uses`
- [ ] [macros] evaluate support for `non_constant_identifier_names`
- [ ] [macros] evaluate support for `noop_primitive_operations`
- [ ] [macros] evaluate support for `null_check_on_nullable_type_parameter`
- [ ] [macros] evaluate support for `null_closures`
- [ ] [macros] evaluate support for `omit_local_variable_types`
- [ ] [macros] evaluate support for `one_member_abstracts`
- [ ] [macros] evaluate support for `only_throw_errors`
- [ ] [macros] evaluate support for `overridden_fields`
- [ ] [macros] evaluate support for `package_api_docs`
- [ ] [macros] evaluate support for `package_names`
- [ ] [macros] evaluate support for `package_prefixed_library_names`
- [ ] [macros] evaluate support for `parameter_assignments`
- [ ] [macros] evaluate support for `prefer_adjacent_string_concatenation`
- [ ] [macros] evaluate support for `prefer_asserts_in_initializer_lists`
- [ ] [macros] evaluate support for `prefer_asserts_with_message`
- [ ] [macros] evaluate support for `prefer_collection_literals`
- [ ] [macros] evaluate support for `prefer_conditional_assignment`
- [ ] [macros] evaluate support for `prefer_const_constructors`
- [ ] [macros] evaluate support for `prefer_const_constructors_in_immutables`
- [ ] [macros] evaluate support for `prefer_const_declarations`
- [ ] [macros] evaluate support for `prefer_const_literals_to_create_immutables`
- [ ] [macros] evaluate support for `prefer_constructors_over_static_methods`
- [ ] [macros] evaluate support for `prefer_contains`
- [ ] [macros] evaluate support for `prefer_double_quotes`
- [ ] [macros] evaluate support for `prefer_expression_function_bodies`
- [ ] [macros] evaluate support for `prefer_final_fields`
- [ ] [macros] evaluate support for `prefer_final_in_for_each`
- [ ] [macros] evaluate support for `prefer_final_locals`
- [ ] [macros] evaluate support for `prefer_final_parameters`
- [ ] [macros] evaluate support for `prefer_for_elements_to_map_fromIterable`
- [ ] [macros] evaluate support for `prefer_foreach`
- [ ] [macros] evaluate support for `prefer_function_declarations_over_variables`
- [ ] [macros] evaluate support for `prefer_generic_function_type_aliases`
- [ ] [macros] evaluate support for `prefer_if_elements_to_conditional_expressions`
- [ ] [macros] evaluate support for `prefer_if_null_operators`
- [ ] [macros] evaluate support for `prefer_initializing_formals`
- [ ] [macros] evaluate support for `prefer_inlined_adds`
- [ ] [macros] evaluate support for `prefer_int_literals`
- [ ] [macros] evaluate support for `prefer_interpolation_to_compose_strings`
- [ ] [macros] evaluate support for `prefer_is_empty`
- [ ] [macros] evaluate support for `prefer_is_not_empty`
- [ ] [macros] evaluate support for `prefer_is_not_operator`
- [ ] [macros] evaluate support for `prefer_iterable_whereType`
- [ ] [macros] evaluate support for `prefer_mixin`
- [ ] [macros] evaluate support for `prefer_null_aware_method_calls`
- [ ] [macros] evaluate support for `prefer_null_aware_operators`
- [ ] [macros] evaluate support for `prefer_relative_imports`
- [ ] [macros] evaluate support for `prefer_single_quotes`
- [ ] [macros] evaluate support for `prefer_spread_collections`
- [ ] [macros] evaluate support for `prefer_typing_uninitialized_variables`
- [ ] [macros] evaluate support for `prefer_void_to_null`
- [ ] [macros] evaluate support for `provide_deprecation_message`
- [ ] [macros] evaluate support for `public_member_api_docs`
- [ ] [macros] evaluate support for `recursive_getters`
- [ ] [macros] evaluate support for `require_trailing_commas`
- [ ] [macros] evaluate support for `secure_pubspec_urls`
- [ ] [macros] evaluate support for `sized_box_for_whitespace`
- [ ] [macros] evaluate support for `sized_box_shrink_expand`
- [ ] [macros] evaluate support for `slash_for_doc_comments`
- [ ] [macros] evaluate support for `sort_child_properties_last`
- [ ] [macros] evaluate support for `sort_constructors_first`
- [ ] [macros] evaluate support for `sort_pub_dependencies`
- [ ] [macros] evaluate support for `sort_unnamed_constructors_first`
- [ ] [macros] evaluate support for `test_types_in_equals`
- [ ] [macros] evaluate support for `throw_in_finally`
- [ ] [macros] evaluate support for `tighten_type_of_initializing_formals`
- [ ] [macros] evaluate support for `type_annotate_public_apis`
- [ ] [macros] evaluate support for `type_init_formals`
- [ ] [macros] evaluate support for `type_literal_in_constant_pattern`
- [ ] [macros] evaluate support for `unawaited_futures`
- [ ] [macros] evaluate support for `unnecessary_await_in_return`
- [ ] [macros] evaluate support for `unnecessary_brace_in_string_interps`
- [ ] [macros] evaluate support for `unnecessary_breaks`
- [ ] [macros] evaluate support for `unnecessary_const`
- [ ] [macros] evaluate support for `unnecessary_constructor_name`
- [ ] [macros] evaluate support for `unnecessary_final`
- [ ] [macros] evaluate support for `unnecessary_getters_setters`
- [ ] [macros] evaluate support for `unnecessary_lambdas`
- [ ] [macros] evaluate support for `unnecessary_late`
- [ ] [macros] evaluate support for `unnecessary_library_directive`
- [ ] [macros] evaluate support for `unnecessary_new`
- [ ] [macros] evaluate support for `unnecessary_null_aware_assignments`
- [ ] [macros] evaluate support for `unnecessary_null_aware_operator_on_extension_on_nullable`
- [ ] [macros] evaluate support for `unnecessary_null_checks`
- [ ] [macros] evaluate support for `unnecessary_null_in_if_null_operators`
- [ ] [macros] evaluate support for `unnecessary_nullable_for_final_variable_declarations`
- [ ] [macros] evaluate support for `unnecessary_overrides`
- [ ] [macros] evaluate support for `unnecessary_parenthesis`
- [ ] [macros] evaluate support for `unnecessary_raw_strings`
- [ ] [macros] evaluate support for `unnecessary_statements`
- [ ] [macros] evaluate support for `unnecessary_string_escapes`
- [ ] [macros] evaluate support for `unnecessary_string_interpolations`
- [ ] [macros] evaluate support for `unnecessary_this`
- [ ] [macros] evaluate support for `unnecessary_to_list_in_spreads`
- [ ] [macros] evaluate support for `unreachable_from_main`
- [ ] [macros] evaluate support for `unrelated_type_equality_checks`
- [ ] [macros] evaluate support for `unsafe_html`
- [ ] [macros] evaluate support for `use_build_context_synchronously`
- [ ] [macros] evaluate support for `use_colored_box`
- [ ] [macros] evaluate support for `use_decorated_box`
- [ ] [macros] evaluate support for `use_enums`
- [ ] [macros] evaluate support for `use_full_hex_values_for_flutter_colors`
- [ ] [macros] evaluate support for `use_function_type_syntax_for_parameters`
- [ ] [macros] evaluate support for `use_if_null_to_convert_nulls_to_bools`
- [ ] [macros] evaluate support for `use_is_even_rather_than_modulo`
- [ ] [macros] evaluate support for `use_key_in_widget_constructors`
- [ ] [macros] evaluate support for `use_late_for_private_fields_and_variables`
- [ ] [macros] evaluate support for `use_named_constants`
- [ ] [macros] evaluate support for `use_raw_strings`
- [ ] [macros] evaluate support for `use_rethrow_when_possible`
- [ ] [macros] evaluate support for `use_setters_to_change_properties`
- [ ] [macros] evaluate support for `use_string_buffers`
- [ ] [macros] evaluate support for `use_string_in_part_of_directives`
- [ ] [macros] evaluate support for `use_super_parameters`
- [ ] [macros] evaluate support for `use_test_throws_matchers`
- [ ] [macros] evaluate support for `use_to_and_as_if_applicable`
- [ ] [macros] evaluate support for `valid_regexps`
- [ ] [macros] evaluate support for `void_checks`

## New Lints

Authors and users of macros (and augmentation classes) might benefit from some new lints.

🚧 Feedback welcome! 🚧 

### Visibility

To whom and under what circumstances should we display diagnostics produced in macro generated files?

- [ ] :☂️ determine what, when and how diagnostics in macro-generated files should be displayed
- [ ] https://github.com/dart-lang/sdk/issues/54875 (pre-release)

/fyi @dart-lang/language-team @bwilkerson @keertip @scheglov @srawlins

**Comment by rrousselGit** [comment]
If this is about running lints on generated code, I assume lots of those probably should not apply.

In particular, all the stylistic ones. For instance `avoid_renaming_method_parameters` would be a huge pain for macro authors to handle. Or `prefer_double_quotes` vs `prefer_single_quotes` doesn't have a finite answer.
